Gabe actually trying (hell yeah) (#61)
* assign, declare, return work. if is a maybe

* a bunch working

this doesnt work

;; (check-equal? (M_state_if '(if '(< x 9) '(begin (= x (+ x 1)))) state (lambda (v) v)) '(((x y a) (6 12 true)))) ;; error

* final if working

* yo gaba gaba

* just un commmenting some more tests

* break working in if (NOT WHILE)

* while working

not pretty tho

* a bit clean

* continue working

* made some old tests work with lambda v

* fixed interpreter (had to add more lambdas)

* all part 1 passing

* fixed which tests actually fail and which dont

* added some more return tests

* show which return is failing

* added a million returns

* cant get call/cc to work

* HAHA 6 and 7 now work

* befoer start screwing with test 11

* a lot more tests not failing

* maybe test 12 okay?

* test 13 now working

* just move fix for 13 to utils

* i did somethings and now only test 17 and 19 fail

* cleaner version where 17 and 19 fail. also still don't error when use before delcare

* fixed tests

* fds

* clean

* changed title

* technically fixed 19

* added optional extra challenge

* teahadfs

* slight change to try

* changes

* more changes

* some changes to clean

* Pushing test case that is being weird

Nested try/catch

* 19 works properly now

* Updated testing file

* New tests

* EVERYTHING WORKS

* run all tests

---------

Co-authored-by: Gabriel Wolf <gabeericwolf@gmail.com>
Co-authored-by: Ari Glockner <ari@glockners.net>

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -24,8 +24,15 @@ jobs:
           version: '8.11'
 
       - name: Run unit tests
-        run: raco test tests.rkt
+        run: raco test tests-p1.rkt
 
-      - name: Check test results and prevent push on failure
+      - name: Check part 1 test results and prevent push on failure
         if: ${{ failure() }}
-        run: echo "Tests failed. Changes cannot be pushed to main." && exit 1
+        run: echo "Part 1 tests failed. Changes cannot be pushed to main." && exit 1
+
+      - name: Run unit tests
+        run: raco test tests-p2.rkt
+
+      - name: Check part 2 test results and prevent push on failure
+        if: ${{ failure() }}
+        run: echo "Part 2 tests failed. Changes cannot be pushed to main." && exit 1
